# 服务器配置
server:
  port: 16999

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qiniuyun?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # 邮件配置
  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:1653719029@qq.com}
    password: ${MAIL_PASSWORD:zhjwlugiiyzyjjab}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${MAIL_HOST:smtp.qq.com}
    # 邮件模板配置
    template:
      from: ${MAIL_FROM:${spring.mail.username}}
      from-name: ${MAIL_FROM_NAME:RolePlay验证码}

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.aichat.roleplay.model
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

# LangChain4j OpenAI配置 - 使用七牛代理
langchain4j:
  open-ai:
    chat-model:
      base-url: https://openai.qiniu.com/v1
      api-key: ${OPENAI_API_KEY:sk-ab8cb5765e0aba823f22f5701c30a4c06a97f3d25846bc349bc931484599aac4}
      model-name: MiniMax-M1
      temperature: 0.7

# 日志配置
logging:
  level:
    root: INFO
    com.aichat.roleplay: DEBUG