# 服务器配置
server:
  port: 16999

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qiniuyun?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # 邮件配置
  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:1653719029@qq.com}
    password: ${MAIL_PASSWORD:zhjwlugiiyzyjjab}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${MAIL_HOST:smtp.qq.com}
    template:
      from: ${MAIL_FROM:${spring.mail.username}}
      from-name: ${MAIL_FROM_NAME:RolePlay验证码}

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.aichat.roleplay.model
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

langchain4j:
  open-ai:
    chat-model:
      base-url: https://openai.qiniu.com/v1
      api-key: ${OPENAI_API_KEY:sk-ab8cb5765e0aba823f22f5701c30a4c06a97f3d25846bc349bc931484599aac4}
      model-name: deepseek/deepseek-v3.1-terminus

      temperature: 0.7
    
    # 语音转文字模型配置
    speech-to-text-model:
      base-url: https://openai.qiniu.com/v1
      api-key: ${OPENAI_API_KEY:sk-ab8cb5765e0aba823f22f5701c30a4c06a97f3d25846bc349bc931484599aac4}
      model-name: ${OPENAI_SPEECH_TO_TEXT_MODEL:asr}
    
    # 文字转语音模型配置  
    text-to-speech-model:
      base-url: https://openai.qiniu.com/v1
      api-key: ${OPENAI_API_KEY:sk-ab8cb5765e0aba823f22f5701c30a4c06a97f3d25846bc349bc931484599aac4}
      model-name: ${OPENAI_TEXT_TO_SPEECH_MODEL:tts}
      voice: ${OPENAI_TTS_VOICE:alloy}

# 文件存储配置
file:
  storage:
    upload-url: ${FILE_UPLOAD_URL:http://111.62.241.115/upload.php}  # 远程上传接口
    base-url: ${FILE_STORAGE_URL:http://111.62.241.115}   # 远程访问地址

# 日志配置
logging:
  level:
    root: INFO
    com.aichat.roleplay: DEBUG