# 服务器配置
server:
  port: 16999

# 数据库配置
spring:
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB      # 单个文件最大大小
      max-request-size: 10MB   # 整个请求最大大小
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/qiniuyun?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:} #环境变量中配置自己的db密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # 邮件配置
  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:1653719029@qq.com}
    password: ${MAIL_PASSWORD:zhjwlugiiyzyjjab}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${MAIL_HOST:smtp.qq.com}
    template:
      from: ${MAIL_FROM:${spring.mail.username}}
      from-name: ${MAIL_FROM_NAME:RolePlay验证码}

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.aichat.roleplay.model
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

langchain4j:
  open-ai:
    chat-model:
      base-url: https://openai.qiniu.com/v1
      api-key: ${OPENAI_API_KEY:sk-ab8cb5765e0aba823f22f5701c30a4c06a97f3d25846bc349bc931484599aac4}
      model-name: deepseek-v3-0324
      max-tokens: 4096
      temperature: 0.5
    
    # 语音转文字模型配置
    speech-to-text-model:
      base-url: https://openai.qiniu.com/v1
      api-key: ${OPENAI_API_KEY:sk-ab8cb5765e0aba823f22f5701c30a4c06a97f3d25846bc349bc931484599aac4}
      model-name: ${OPENAI_SPEECH_TO_TEXT_MODEL:asr}
    
    # 文字转语音模型配置  
    text-to-speech-model:
      base-url: https://openai.qiniu.com/v1
      api-key: ${OPENAI_API_KEY:sk-ab8cb5765e0aba823f22f5701c30a4c06a97f3d25846bc349bc931484599aac4}
      model-name: ${OPENAI_TEXT_TO_SPEECH_MODEL:tts}
      voice: ${OPENAI_TTS_VOICE:alloy}

# 文件存储配置
file:
  storage:
    upload-url: ${FILE_UPLOAD_URL:http://111.62.241.115/upload.php}  # 远程上传接口
    base-url: ${FILE_STORAGE_URL:http://111.62.241.115}   # 远程访问地址

# 头像上传配置
app:
  upload:
    avatar-dir: ${AVATAR_UPLOAD_DIR:frontend/public/avatars}
    avatar-url-prefix: ${AVATAR_URL_PREFIX:http://localhost:5173/avatars}

# 日志配置
logging:
  level:
    root: INFO
    com.aichat.roleplay: DEBUG


reflection:
  enabled: true
  max-retry-count: 3
  reflection-timeout-ms: 30000
  # 关键词文件路径配置
  keyword-files:
    identity-exposure: "anomaly-keywords/identity-exposure.txt"
    role-breaking: "anomaly-keywords/role-breaking.txt"
    over-deflection: "anomaly-keywords/over-deflection.txt"
    technical-exposure: "anomaly-keywords/technical-exposure.txt"
  # 积极关键词 - 根据具体业务场景可配置，默认为空让检测更通用
  positive-keywords: []
  # 异常检测详细配置
  anomaly-detection:
    min-response-length: 5
    max-response-length: 2000
    check-language-consistency: true
    check-role-consistency: true
    anomaly-threshold: 0.4  # 降低阈值，让系统更敏感
    severe-anomaly-threshold: 0.7  # 降低严重阈值

rag:
  max-results: 5
  similarity-threshold: 0.7

# 聊天室协作配置
chatroom:
  collaboration:
    # 选择参与对话的角色数量
    top-k-roles: 2
    # 最大并发角色数量
    max-concurrent-roles: 2
    # 角色选择超时时间（毫秒）
    role-selection-timeout: 100000
    # 流式响应超时时间（毫秒）
    stream-timeout: 600000

